(function(g){var window=this;var Eoa=function(a){if(!a.Ja||!a.Ja.annotations)return null;a=g.p(a.Ja.annotations);for(var b=a.next();!b.done;b=a.next())if(b=b.value,b.playerAnnotationsExpandedRenderer&&b.playerAnnotationsExpandedRenderer.featuredChannel)return b.playerAnnotationsExpandedRenderer;return null},g1=function(a){a.u||(a.u=new g.xn,g.H(a,a.u));
return a.u},h1=function(a){a.R("cardstatechange",g.LK(a)&&g.MK(a)?1:0)},Foa=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.Pi&&a.dataset){if(g.gc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.cd("pollChoiceIndex"))},Goa=function(a){return Math.pow(a,3)},Hoa=function(a){return 3*a*a-2*a*a*a},i1=function(a,b){(0,g.z)(b,function(c){c={csn:a,
ve:g.LA(c),eventType:4};var d={jj:void 0,vh:a};"UNDEFINED_CSN"==a?g.WA("visualElementShown",c,d):g.rr("visualElementShown",c,g.wr,d)})},j1=function(a,b){(0,g.z)(b,function(c){var d=void 0;
d=void 0===d?!1:d;c={csn:a,ve:g.LA(c),eventType:d?16:8};d={jj:void 0,vh:a,VB:d};"UNDEFINED_CSN"==a?g.WA("visualElementHidden",c,d):g.rr("visualElementHidden",c,g.wr,d)})},m1=function(a){a=g.Ma(a);
delete k1[a];g.Wb(k1)&&l1&&l1.stop()},n1=function(){l1||(l1=new g.J(function(){Ioa()},20));
var a=l1;a.isActive()||a.start()},Ioa=function(){var a=(0,g.A)();
g.Ib(k1,function(b){o1(b,a)});
g.Wb(k1)||n1()},p1=function(a,b,c,d){g.mn.call(this);
if(!g.Ha(a)||!g.Ha(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.w=a;this.J=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.H=0;this.D=null},o1=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.H=1E3/(b-a.D);a.D=b;q1(a,a.progress);1==a.progress?(a.o=0,m1(a),a.Wc(),a.A()):1==a.o&&a.er()},q1=function(a,b){g.Ja(a.G)&&(b=a.G(b));
a.coords=Array(a.w.length);for(var c=0;c<a.w.length;c++)a.coords[c]=(a.J[c]-a.w[c])*b+a.w[c]},r1=function(a,b){g.Uj.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.H;this.state=b.o},s1=function(a,b,c,d,e){p1.call(this,b,c,d,e);
this.element=a},t1=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
s1.call(this,a,b,c,d,e)},u1=function(a){g.E.call(this);
this.u=a||window;this.o=[]},Joa=function(a,b,c,d){c=(0,g.x)(c,d||a.u);
b=g.gr(b,"change",c,"iv-card-poll-choice-input");a.o.push(b)},v1=function(a){return a.baseUrl||null},Koa=function(a,b,c){function d(T){var fa=T.hovercardButton;
if(!fa)return null;fa=fa.subscribeButtonRenderer;if(!fa)return null;var Ca=f(fa.unsubscribedButtonText),wc=f(fa.subscribedButtonText);if(fa.subscribed){var lc=f(fa.subscriberCountWithUnsubscribeText);var Yd=f(fa.subscriberCountText)}else lc=f(fa.subscriberCountText),Yd=f(fa.subscriberCountWithSubscribeText);var xc=null;return T.signinEndpoint&&(xc=g.Qb(T,"signinEndpoint","webNavigationEndpointData","url"),!xc)?null:Ca&&(wc||xc)?{subscribed:fa.subscribed,subscribeText:Ca,subscribeCount:lc,unsubscribeText:wc,
unsubscribeCount:Yd,enabled:fa.enabled,signinUrl:xc,classic:T.useClassicSubscribeButton}:null}
function e(T){if(T){var fa=[],Ca=T.videoId;Ca&&fa.push("v="+Ca);(Ca=T.playlistId)&&fa.push("list="+Ca);(T=T.startTimeSeconds)&&fa.push("t="+T);return"/watch?"+fa.join("&")}}
function f(T){if(!T)return null;var fa=T.simpleText;return fa?fa:T.runs?(0,g.ee)(T.runs,function(Ca){return Ca.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var k=b.style,l=b.endpoint||{},m=null,n=null,q=null,t=null,v=null,y=null,C=!1,B=null,G=null,I=null,F=null,M=null;if("VIDEO"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,t=f(b.videoDuration);else if("PLAYLIST"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,v=f(b.playlistLength);else if("CHANNEL"==k){if(C=g.Qb(l,"browseEndpoint","browseId"))y=C,m="/channel/"+y;n=!1;q="new";(C=!!b.isSubscribe)?B=d(b):G=f(b.subscribersText)}else"WEBSITE"==
k?((I=g.Qb(l,"urlEndpoint","url"))&&(m=I),n=!0,q="new",I=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"==k&&(b.productPrice&&b.additionalFeesText&&(F=f(b.productPrice),M=f(b.additionalFeesText)),(a=g.Qb(l,"urlEndpoint","url"))&&(m=a),n=!0,q="new");a=g.Qb(b,"title","accessibility","accessibilityData","label");return{id:"element-"+c,type:k,title:f(b.title),metadata:f(b.metadata),callToAction:f(b.callToAction),ou:b.image,iconUrl:I,left:parseFloat(b.left),width:parseFloat(b.width),top:parseFloat(b.top),
aspectRatio:parseFloat(b.aspectRatio),startMs:parseInt(b.startMs,10),endMs:parseInt(b.endMs,10),videoDuration:t,playlistLength:v,channelId:y,subscribeButton:B,subscribersText:G,isSubscribe:C,targetUrl:m,uD:n,Fb:{itct:b.trackingParams},lM:q,aj:a?a:null,yD:b.isPlaceholder,impressionUrls:(0,g.ee)(b.impressionUrls||[],v1),lD:(0,g.ee)(b.hovercardShowUrls||[],v1),clickUrls:(0,g.ee)(l.loggingUrls||[],v1),visualElement:g.KA(b.trackingParams),productPrice:F,additionalFeesText:M}},w1=function(a,b){var c={};
c.startMs=parseInt(a.startMs,10);c.impressionUrls=(0,g.ee)(a.impressionUrls||[],v1);a.trackingParams&&(c.visualElement=g.KA(a.trackingParams));var d=(0,g.ee)(a.elements||[],function(e,f){return Koa(b,e,f)});
c.elements=(0,g.Td)(d,function(e){return!!e});
return c},x1=function(a){g.AP.call(this,a);
this.A=this.u=null;this.o={};this.D={};this.C=this.w=null;this.H=[];a=a.O();this.J=g.cz(a)||g.ez(a);this.K=!0;this.G=0;this.B=new g.Q(this);g.H(this,this.B);this.B.M(this.player,g.OD("creatorendscreen"),this.hE);this.B.M(this.player,"crx_creatorendscreen",this.iE);this.B.M(this.player,"resize",this.uw);this.B.M(window,"focus",this.hL);this.load();var b=g.Nd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.xi(this,function(){g.Sd(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},y1=function(a){return a.player.getVideoData().ac?"current":a.J?"new":"current"},z1=function(a){return"creator-endscreen-editor"===a.player.O().playerStyle},A1=function(a,b){g.GQ(a.player.app,"creatorendscreen",void 0);
a.w&&(a.w.dispose(),a.w=null,a.C.dispose(),a.C=null);for(var c in a.o)a.o[c].dispose();a.o={};a.D={};0<a.H.length&&(a.H.forEach(function(l){l.dispose()}),a.H.length=0);
a.G=0;if((a.u=b)&&b.elements){Loa(a);c=[];var d=new g.LD(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.O().o||(a.w=new g.W({F:"div",I:"ytp-ce-shadow"}),g.WK(a.player,a.w.element,4),a.C=new g.PL(a.w,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=Moa(a,e);a.o[e.id]=f;a.D[e.id]=e;g.WK(a.player,f.element,4);var k=new g.LD(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);Noa(a,f,e)}g.SK(a.player,
c);a.uw()}},Loa=function(a){var b=g.eB(),c=g.fB();
c&&b&&a.u.visualElement&&g.XA(c,b,[a.u.visualElement],void 0)},Moa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={F:"div",X:["ytp-ce-element","ytp-ce-video"],N:{tabindex:"0","aria-label":b.aj||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-covering-image",N:B1(b)},{F:"div",I:"ytp-ce-covering-shadow-top"},{F:"a",I:"ytp-ce-covering-overlay",N:{href:C1(a,b.targetUrl),tabindex:"-1"},L:[{F:"div",X:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],N:{dir:g.qn(b.title||"")},W:b.title},{F:"div",I:"ytp-ce-video-duration",W:b.videoDuration}]}]};
c=new g.W(c);break;case "PLAYLIST":c={F:"div",X:["ytp-ce-element","ytp-ce-playlist"],N:{tabindex:"0","aria-label":b.aj||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-covering-image",N:B1(b)},{F:"div",I:"ytp-ce-covering-shadow-top"},{F:"a",I:"ytp-ce-covering-overlay",N:{href:C1(a,b.targetUrl),tabindex:"-1"},L:[{F:"div",X:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],N:{dir:g.qn(b.title||"")},W:b.title},{F:"div",I:"ytp-ce-playlist-count",L:[{F:"div",
I:"ytp-ce-playlist-icon"},{F:"div",I:"ytp-ce-playlist-count-text",W:b.playlistLength}]}]}]};c=new g.W(c);break;case "CHANNEL":c={F:"div",X:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],N:{tabindex:"0","aria-label":b.aj||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-expanding-overlay",L:[{F:"div",I:"ytp-ce-expanding-overlay-hider"},{F:"div",I:"ytp-ce-expanding-overlay-background"},{F:"div",I:"ytp-ce-expanding-overlay-content",
L:[{F:"div",I:"ytp-ce-expanding-overlay-body",L:[{F:"div",I:"ytp-ce-expanding-overlay-body-padding",L:[{F:"a",X:["ytp-ce-channel-title","ytp-ce-link"],N:{href:C1(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.qn(b.title||"")},W:b.title},b.subscribeButton?{F:"div",I:"ytp-ce-subscribe-container",L:[{F:"div",I:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{F:"div",I:"ytp-ce-channel-subscribers-text",W:b.subscribersText}:"",b.metadata?{F:"div",X:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
W:b.metadata}:""]}]}]}]},{F:"div",I:"ytp-ce-expanding-image",N:B1(b)}]};c=new g.W(c);var d=g.yd(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.K(d,"ytp-ce-subscribe-button");if(a.player.O().o){var e=null;var f=b.Fb.itct}else e="endscreen",f=null;e=new g.MQ(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.H.push(e)}break;case "WEBSITE":c={F:"div",X:["ytp-ce-element","ytp-ce-website"],N:{tabindex:"0","aria-label":b.aj||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-expanding-overlay",L:[{F:"div",I:"ytp-ce-expanding-overlay-hider"},{F:"div",I:"ytp-ce-expanding-overlay-background"},{F:"div",I:"ytp-ce-expanding-overlay-content",L:[{F:"div",I:"ytp-ce-expanding-overlay-body",
L:[{F:"div",I:"ytp-ce-expanding-overlay-body-padding",L:[{F:"div",I:"ytp-ce-website-title",N:{dir:g.qn(b.title||"")},W:b.title},{F:"div",I:"ytp-ce-website-metadata",W:b.metadata},{F:"a",X:["ytp-ce-website-goto","ytp-ce-link"],N:{href:C1(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{F:"div",I:"ytp-ce-expanding-image",N:B1(b)},{F:"div",I:"ytp-ce-expanding-icon",N:D1(b.iconUrl)}]};c=new g.W(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&b.additionalFeesText&&(c={F:"div",
I:"ytp-ce-merchandise-price-container",L:[{F:"div",I:"ytp-ce-merchandise-price",W:b.productPrice},{F:"div",I:"ytp-ce-merchandise-additional-fees",W:b.additionalFeesText}]}),c={F:"div",X:["ytp-ce-element","ytp-ce-merchandise"],N:{tabindex:"0","aria-label":b.aj||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-expanding-overlay",L:[{F:"div",I:"ytp-ce-expanding-overlay-hider"},{F:"div",I:"ytp-ce-expanding-overlay-background"},{F:"div",I:"ytp-ce-expanding-overlay-content",
L:[{F:"div",I:"ytp-ce-expanding-overlay-body",L:[{F:"div",I:"ytp-ce-expanding-overlay-body-padding",L:[{F:"div",I:"ytp-ce-merchandise-title",N:{dir:g.qn(b.title||"")},W:b.title},c,{F:"div",I:"ytp-ce-merchandise-metadata",W:b.metadata},{F:"div",I:"ytp-ce-merchandise-expanded-cta-container",L:[{F:"a",X:["ytp-ce-merchandise-goto","ytp-ce-link"],N:{href:C1(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction},{F:"div",I:"ytp-ce-merchandise-cta-external"}]}]}]}]}]},{F:"div",I:"ytp-ce-expanding-image",
N:B1(b)},{F:"div",I:"ytp-ce-merchandise-invideo-cta-container",L:[{F:"div",I:"ytp-ce-merchandise-invideo-cta",W:b.callToAction}]}]},c=new g.W(c)}b.yD&&g.K(c.element,"ytp-ce-placeholder");return c},B1=function(a){if(a.ou)var b=a.ou.thumbnails;
return D1(b?b[b.length-1].url:null)},D1=function(a){return a?{style:"background-image: url("+a+")"}:{}},Noa=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.ga("mouseenter",(0,g.x)(a.nq,a,b,c));b.ga("mouseleave",(0,g.x)(a.kr,a,b,c));a.player.O().o||b.ga("click",(0,g.x)(function(l){g.K(l.element,"ytp-ce-element-hover")},a,b));
b.ga("click",(0,g.x)(a.Sx,a,c));b.ga("keypress",(0,g.x)(a.Sx,a,c));b.ga("focus",(0,g.x)(function(l,m){this.nq(l,m)},a,b,c));
b.ga("blur",(0,g.x)(function(l,m){this.kr(l,m)},a,b,c));
b.ga("touchstart",(0,g.x)(a.nq,a,b,c));var f=g.Bd("ytp-ce-expanding-overlay-hider",b.element);f&&b.M(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.kn(b.element,"ytp-ce-element-hover");g.kn(b.element,"ytp-ce-force-expand")});
b.ga("keydown",(0,g.x)(function(l,m){this.K=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.x)(function(l,m,n){this.G+=n;0<this.G?(g.K(l.element,"ytp-ce-force-expand"),E1(this,m.id,!0)):(g.kn(l.element,"ytp-ce-force-expand"),g.kn(l.element,"ytp-ce-element-hover"),E1(this,m.id,!1))},a,b,c);
c=(0,g.x)(function(l,m){m&&(l.ga("blur",g.Na(function(){"none"!=m.style.display&&a.K&&m.focus()})),l.M(m,"focus",d),l.M(m,"blur",e))},a,b);
c(g.Bd("ytp-sb-subscribe",b.element));c(g.Bd("ytp-sb-unsubscribe",b.element));b.ga("focus",d);b.ga("blur",e)},C1=function(a,b){var c=a.player.O();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.Gz(c)+b}else return"";return b},E1=function(a,b,c){a.w&&(c?a.C.show():a.C.hide());
for(var d in a.o)d!=b&&g.L(a.o[d].element,"ytp-ce-element-shadow-show",c)},F1=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||z1(a))c&&c();else{b=Ooa(a,b);var e=0,f=!1,k=new g.J(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.Up(b[a],d)}},G1=function(a,b,c){F1(a,b.clickUrls,c);
(a=g.fB())&&b.uD&&g.ZA(a,b.visualElement)},Ooa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(Poa(b[e],c));return d},Poa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},H1=function(a){return g.Ha(a)&&a.length?a[0]:a},I1=function(a){return"string"===typeof a?a:""},J1=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},Roa=function(a){var b=Qoa;
if(null==a)return null;if(g.Ia(a)){var c=[];(0,g.z)(a,function(d){(d=b(d))&&c.push(d)});
return c}return(a=b(a))?[a]:[]},Soa=function(a){this.externalId=a},K1=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},L1=function(a){if(!a)return null;
var b=g.Bc(I1(a.value));b=g.zc(b);if(!b)return null;var c=J1(a.target,Toa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new K1(b,c,"true"==d||"false"==d?"true"==d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},M1=function(a){return a.value?a.value:null},N1=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},Qoa=function(a){if(!a)return null;
var b=J1(a.type,Uoa),c=J1(a.trigger,Voa),d=H1(a.url);d=L1(d?d:null);a=H1(a.subscribeData);var e=a?a:null;e?(a=I1(e.external_user_id),e=I1(e.subscription_token),a=a&&e?new Soa(a):null):a=null;return b?new N1(b,c,d,a):null},O1=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.o=d||[];this.data=e},P1=function(a){return(a=Woa(a,function(b){return"openUrl"==b.type&&null!=b.url}))?a.url:null},Woa=function(a,b){return g.Ua(a.o,b,void 0)},Q1=function(a,b){return a.id.replace(/[^a-z0-9-]/gi,"-")+"-"+b.toString()},Xoa=function(a,b){this.merchant=a;
this.price=b},Yoa=function(a){this.o=a},Zoa=function(a,b,c){b&&(c?R1(a,(0,g.ee)(b,g.Na(function(d,e){return g.Vm(e,d)},c))):R1(a,b))},R1=function(a,b,c,d){var e=1,f=-1;
if(c){var k=!1;var l=function(){e--;e||k||(clearTimeout(f),k=!0,c())};
f=setTimeout(function(){k=!0;c()},1E3)}(0,g.z)(b||[],function(m){e++;
g.Up(m,l)});
d&&(e++,0!=d&&a.o.sendVideoStatsEngageEvent(d,l))},$oa=function(a,b,c,d,e,f,k){this.o=a;
this.w=b;this.Xa=c;this.videoData=d;this.logger=e;this.ca=f;this.u=k},S1=function(a,b){this.o=a;
this.w=b},bpa=function(a,b){var c=[];
(0,g.z)(b.choices,function(k){c.push(apa(b,k))},a);
var d={F:"ul",N:{role:"radiogroup"},L:c},e={};b.Ah&&(e["aria-label"]=g.vM("$POLL_TITLE - Sign in to vote.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{F:"div",I:"iv-card-content",L:[T1("h2",e,b.title),{F:"form",L:[{F:"fieldset",L:[d]}]}]}];b.Ah&&(f.push("iv-card-unavailable"),d.push({F:"div",X:["iv-card-sign-in"],L:[{F:"h2",W:"Want to vote?"},{F:"a",X:["iv-card-sign-in-button","iv-button"],N:{href:M1(b.Ah)},L:[{F:"span",X:["iv-button-content"],W:"Sign in"}]}]}));f=new g.W({F:"div",
X:f,L:d});d=f.element;U1(b,d);Joa(a.o.o,d,g.Na(a.A,b),a);(0,g.z)(g.zd("iv-card-poll-choice-input",d),function(k){this.o.o.ga(k,"focus",g.Na(this.u,!0));this.o.o.ga(k,"blur",g.Na(this.u,!1))},a);
b.Ah&&(d=g.Bd("iv-card-sign-in-button",d),a.w(d,b.Ah,b.id,b.Fb,b.tc.click,5));return f},Y1=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.CM?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.xD&&b.Mt?{F:"span",X:d,N:e,W:b.Mt}:"";c={F:"div",X:["iv-card",c],L:[{F:"a",I:"iv-click-target",N:{href:M1(b.url)},L:[V1(b.Dh,d?{F:"div",I:"iv-card-image-text",L:[d,b.priceText]}:""),{F:"div",I:"iv-card-content",L:[{F:"h2",I:"iv-card-primary-link",W:b.title},W1(a,b)]}]}]};c=new g.W(c);X1(a,g.zd("iv-click-target",c.element),b,b.url);return c},Z1=function(a){return a.customMessage?
T1("div","iv-card-message",a.customMessage):""},V1=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{F:"div",I:"iv-card-image",N:{style:c},L:d}},W1=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.z)(b.metaInfo,function(d){c.push(T1("li","",d))},a);
return{F:"ul",I:"iv-card-meta-info",L:c}},apa=function(a,b){return{F:"li",
I:Q1(a,b.index),L:[{F:"label",L:[{F:"input",I:"iv-card-poll-choice-input",N:{type:"checkbox",role:"radio",name:a.id.replace(/[^a-z0-9-]/gi,"-")+b.index.toString(),value:b.index.toString(),"data-poll-choice-index":b.index.toString()}},{F:"span",I:"iv-card-poll-choice-text",L:[{F:"span",I:"iv-card-poll-choice-percent"},T1("span",void 0,b.desc)]}]},{F:"div",I:"iv-card-poll-result",L:[{F:"div",I:"iv-card-poll-result-bar"}]}]}},T1=function(a,b,c){b?"string"===typeof b?b={"class":b}:g.Ha(b)&&(b={"class":b.join(" ")}):
b={};
b.dir=g.qn(c);return{F:a,N:b,W:c}},$1=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.xl&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.xl+");");c.dir=g.qn(a.customMessage);var d=[{F:"span",W:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({F:"span",I:"iv-card-link-icon"}));return{F:"div",X:b,N:c,L:d}},U1=function(a,b){var c=0;
(0,g.z)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.Bd(Q1(a,e.index),b);e=e.count/c;null==a.ee&&(e=0);g.L(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.ee==d);f.getElementsByTagName("input")[0].checked=a.ee==d;var k=Math.floor(100*e).toFixed(0),l=g.Bd("iv-card-poll-choice-percent",f);g.Xd(l,g.vM("$PERCENT%",{PERCENT:k}));f=g.Bd("iv-card-poll-result-bar",f);g.ag(f,"transform","scaleX("+e.toFixed(2)+")")}g.L(b,"iv-card-poll-voted",null!=a.ee);g.L(b,"iv-card-poll-expanded",
null!=a.ee&&1<a.choices.length)},X1=function(a,b,c,d){d&&(0,g.z)(b,function(e){this.w(e,d,c.id,c.Fb,c.tc.click,5)},a)},a2=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},cpa=function(a,b){return b?b:a2(a)?"current":"new"},b2=function(a,b){g.E.call(this);
this.o=a;this.context=b;this.xs=!1},dpa=function(a,b,c,d,e){var f=M1(b);
if(f){var k=cpa(f,b.target),l=(0,g.x)(function(){b.o&&this.context.ca.pauseVideo();var m=this.context.videoData.ac||!1,n=g.fp(f||"");m&&n&&(n.v||n.list)?g.kT(this.context.ca.app,n.v,c,n.list,!1,void 0):g.BM(f||"","current"==k?"_top":void 0,c)},a);
"new"==k&&(l(),l=null);R1(a.context.logger,d,l,e);a2(f)||(a=g.fB(),d=c.itct,a&&d&&g.ZA(a,g.KA(d)))}},c2=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},d2=function(a,b,c){return{Dv:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
Ez:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
Qn:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl})}},g2=function(a,b,c){b2.call(this,b,c);
var d=this;this.w=a;this.Z=this.ya=this.C=this.xa=!1;this.aa=null;this.da=new g.J(g.Ea,c.Xa.dd?4E3:3E3);g.H(this,this.da);this.la=new g.J(g.Ea);g.H(this,this.la);this.H=new S1(c,(0,g.x)(this.Li,this),(0,g.x)(this.Cm,this));this.T=new g.W({F:"div",I:"iv-drawer",N:{id:"iv-drawer"},L:[{F:"div",I:"iv-drawer-header",N:{"aria-role":"heading"},L:[{F:"span",I:"iv-drawer-header-text"},{F:"button",X:["iv-drawer-close-button","ytp-button"],N:{"aria-label":"Hide cards",tabindex:"0"}}]},{F:"div",I:"iv-drawer-content"}]});
g.H(this,this.T);this.D=this.T.element;this.oa=new g.PL(this.T,330);g.H(this,this.oa);this.wa=g.Bd("iv-drawer-header-text",this.D);this.B=g.Bd("iv-drawer-content",this.D);this.A=[];this.na=this.P=this.G=this.fa=this.u=null;this.V=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.ya&&e2(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.ya=d.C)&&f2(d)});
this.U=this.J=this.ba=null;this.K=0},epa=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){e2(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){f2(a)});
var c=b.data.headerText;g.Xd(a.wa,c);a.P&&a.P.setAttribute("title",c);a.ba=g.KA(b.data.trackingParams);a.U=g.KA(b.data.closeTrackingParams);a.J=g.KA(b.data.iconTrackingParams)},fpa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.K,type:"simple",teaserText:g.WB(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Fb:h2(a,c,b),sponsored:!1,tc:d2(d,e,d.command),Cd:d.trackingParams?g.KA(d.trackingParams):null,zd:e.trackingParams?
g.KA(e.trackingParams):null,Qc:f&&f.trackingParams?g.KA(f.trackingParams):null,imageUrl:d.image.thumbnails[0].url,displayDomain:d.displayDomain?g.WB(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,xl:null,title:d.title?g.WB(d.title):"",customMessage:d.callToAction?g.WB(d.callToAction):"",url:d.command.urlEndpoint.url?L1({pause_on_navigation:!a.context.videoData.ra,target:"new",value:d.command.urlEndpoint.url}):null};i2(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.K,type:"collaborator",teaserText:g.WB(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Fb:h2(a,c,b),sponsored:!1,tc:d2(d,e,d.endpoint),Cd:d.trackingParams?g.KA(d.trackingParams):null,zd:e.trackingParams?g.KA(e.trackingParams):null,Qc:f&&f.trackingParams?g.KA(f.trackingParams):
null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.WB(d.customText):null,Hy:d.channelAvatar.thumbnails[0].url,title:d.channelName?g.WB(d.channelName):"",metaInfo:[d.subscriberCountText?g.WB(d.subscriberCountText):""],url:L1({pause_on_navigation:!a.context.videoData.ra,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};i2(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.K,type:"playlist",teaserText:g.WB(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Fb:h2(a,c,b),sponsored:!1,tc:d2(d,e,d.action),Cd:d.trackingParams?g.KA(d.trackingParams):null,zd:e.trackingParams?g.KA(e.trackingParams):null,Qc:f&&f.trackingParams?g.KA(f.trackingParams):
null,Dh:d.playlistThumbnail.thumbnails[0].url,customMessage:d.customMessage?g.WB(d.customMessage):null,playlistVideoCount:g.WB(d.playlistVideoCount),title:d.playlistTitle?g.WB(d.playlistTitle):"",metaInfo:[d.channelName?g.WB(d.channelName):"",d.videoCountText?g.WB(d.videoCountText):""],url:L1({pause_on_navigation:!a.context.videoData.ra,target:"new",value:c2(d.action)})};i2(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.K,type:"video",teaserText:g.WB(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Fb:h2(a,c,b),sponsored:!1,tc:d2(d,e,d.action),Cd:d.trackingParams?g.KA(d.trackingParams):null,zd:e.trackingParams?g.KA(e.trackingParams):null,Qc:f&&f.trackingParams?g.KA(f.trackingParams):null,Dh:d.videoThumbnail.thumbnails[0].url,
videoDuration:d.lengthString?g.WB(d.lengthString):null,customMessage:d.customMessage?g.WB(d.customMessage):null,title:d.videoTitle?g.WB(d.videoTitle):"",metaInfo:[d.channelName?g.WB(d.channelName):"",d.viewCountText?g.WB(d.viewCountText):""],isLiveNow:!!d.badge,url:L1({pause_on_navigation:!a.context.videoData.ra,target:"new",value:c2(d.action)})};i2(a,c)}a.K++},h2=function(a,b,c){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId,itct:c.trackingParams}},k2=function(a,b){var c=gpa(a,b);
c&&(c==a.u&&(a.u=null),a.w.removeCueRange(c.card.id),g.Sd(c.Mo),g.ab(a.A,c),a.zl(),j2(a))},e2=function(a,b,c){if(!a.C){a.oa.show();
a.fa=new g.J(function(){g.K(a.context.ca.getRootNode(),"ytp-iv-drawer-open")},0);
a.fa.start();a.aa=g.Yq(a.B,"mousewheel",(0,g.x)(a.EE,a));a.C=!0;var d=g.fB();d&&a.ba&&a.U&&i1(d,[a.ba,a.U]);var e={TRIGGER_TYPE:b};(0,g.z)(a.A,function(f){f.gw||(f.gw=!0,Zoa(a.context.logger,f.card.tc.Dv,e));d&&i1(d,[f.card.Cd])});
h1(a.w);c&&(a.G=new g.J(function(){a.ea=a.P;a.na.focus()},330),a.G.start())}},f2=function(a){a.C&&(a.oa.hide(),g.Zq(a.aa),a.aa=null,g.kn(a.context.ca.getRootNode(),"ytp-iv-drawer-open"),a.C=!1,h1(a.w),a.G&&a.G.stop(),a.G=new g.J(function(){a.ea&&(a.ea.focus(),a.ea=null)},330),a.G.start())},hpa=function(a){var b=g.Bd("iv-drawer-close-button",a.D);
a.context.o.ga(b,"click",a.EB,a);a.context.o.ga(a.B,"touchend",function(){a.da.start()});
a.context.o.ga(a.B,"scroll",a.SB,a);a.context.u.subscribe("onHideControls",function(){a.Z=!0});
a.context.u.subscribe("onShowControls",function(){a.Z=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Z=g.hn(a.w.getRootNode(),"ytp-autohide")});
a.V.push(g.Io("iv-button-shown",a.JD,a));a.V.push(g.Io("iv-button-hidden",a.ID,a));a.V.push(g.Io("iv-teaser-shown",a.MD,a));a.V.push(g.Io("iv-teaser-hidden",a.LD,a));a.V.push(g.Io("iv-teaser-clicked",a.KD,a))},i2=function(a,b){a.xa||(g.jn(a.o,["html5-stop-propagation",
"iv-drawer-manager"]),g.WK(a.w,a.D,5),hpa(a),a.P=g.Bd("ytp-cards-button",a.w.getRootNode()),a.na=g.Bd("iv-drawer-close-button",a.D),a.xa=!0);k2(a,b.id);var c=ipa(a,b);if(c){var d={card:b,Mo:c.element,gw:!1},e=jpa(a,d);g.gb(a.A,e,0,d);c.o(a.B,e);a.zl();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,g.Na(a.UL,d)):(c=1E3*a.context.ca.getCurrentTime(),5E3>c&&c>b.startMs&&a.mz(d),a.addCueRange(b.startMs,b.startMs+1,b.id,g.Na(a.mz,d)),j2(a))}},ipa=function(a,b){switch(b.type){case "simple":var c=
a.H;
var d=b.displayDomain?{F:"div",I:"iv-card-image-text",W:b.displayDomain}:"";var e=$1(b);d={F:"div",X:["iv-card"],L:[{F:"a",I:"iv-click-target",N:{href:M1(b.url)},L:[V1(b.imageUrl,d),{F:"div",I:"iv-card-content",L:[T1("h2",void 0,b.title),e]}]}]};d=new g.W(d);X1(c,g.zd("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.H,d={F:"div",X:["iv-card","iv-card-channel"],L:[{F:"a",X:["iv-click-target"],N:{href:M1(b.url),"data-ytid":b.channelId},L:[V1(b.Hy),{F:"div",I:"iv-card-content",
L:[Z1(b),{F:"h2",I:"iv-card-primary-link",W:b.title},W1(c,b)]}]}]},d=new g.W(d),X1(c,g.zd("iv-click-target",d.element),b,b.url),d;case "episode":return Y1(a.H,b,"iv-card-episode");case "movie":return Y1(a.H,b,"iv-card-movie");case "playlist":return c=a.H,d={F:"div",X:["iv-card","iv-card-playlist"],L:[{F:"a",I:"iv-click-target",N:{href:M1(b.url)},L:[V1(b.Dh,{F:"div",I:"iv-card-image-overlay",L:[{F:"span",I:"iv-card-playlist-video-count",W:b.playlistVideoCount}]}),{F:"div",I:"iv-card-content",L:[Z1(b),
T1("h2","iv-card-primary-link",b.title),W1(c,b)]}]}]},d=new g.W(d),X1(c,g.zd("iv-click-target",d.element),b,b.url),d;case "poll":return bpa(a.H,b);case "productListing":c=a.H;var f=!g.Ya(b.offers);d=["iv-card"];e="";var k=$1(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",f=b.offers[0],k=[],f.price&&k.push({F:"div",I:"iv-card-offer-price",W:f.price}),f.merchant&&k.push({F:"div",I:"iv-card-offer-merchant",W:f.merchant}),k={F:"div",L:k});d={F:"div",X:d,N:{tabindex:"0"},L:[{F:"a",X:["iv-card-image",
"iv-click-target"],N:{style:"background-image: url("+b.imageUrl+");",href:M1(b.url),"aria-hidden":"true",tabindex:"-1"}},{F:"div",I:"iv-card-content",L:[b.sponsored?{F:"div",I:"iv-card-sponsored",L:["Sponsored",{F:"div",I:"iv-ad-info-container",L:[{F:"div",I:"iv-ad-info",W:"{{adInfo}}"},{F:"div",I:"iv-ad-info-icon-container",L:[{F:"div",I:"iv-ad-info-icon"},{F:"div",I:"iv-ad-info-callout"}]}]}]}:"",{F:"a",I:"iv-click-target",N:{href:M1(b.url)},L:[T1("h2",e,b.title),k]}]}]};d=new g.W(d);e=g.Nd("span");
g.Xd(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");d.jb(e,"adInfo");X1(c,g.zd("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.H,d=b.isLiveNow?{F:"span",X:["yt-badge","yt-badge-live"],W:"LIVE NOW"}:"",d={F:"div",X:["iv-card","iv-card-video"],L:[{F:"a",I:"iv-click-target",N:{href:M1(b.url)},L:[V1(b.Dh,b.videoDuration?{F:"span",I:"iv-card-video-duration",W:b.videoDuration}:""),{F:"div",I:"iv-card-content",
L:[Z1(b),T1("h2","iv-card-primary-link",b.title),W1(c,b),d]}]}]},d=new g.W(d),X1(c,g.zd("iv-click-target",d.element),b,b.url),d}return null},jpa=function(a,b){if(0==a.A.length)return 0;
var c=g.Va(a.A,function(d){return b.card.startMs>d.card.startMs||b.card.startMs==d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1==c?0:c+1},kpa=function(a){return a.u?"productListing"==a.u.card.type:(0,g.$g)(a.A,function(b){return"productListing"==b.card.type})},j2=function(a){g.L(a.w.getRootNode(),"ytp-cards-shopping-active",kpa(a))},l2=function(a,b){if(a.T.Ha()){var c=new p1([0,
a.B.scrollTop],[0,b.Mo.offsetTop],600,Hoa);a.context.w.ga(c,"animate",function(d){a.B.scrollTop=d.y});
a.context.w.ga(c,"finish",function(d){a.B.scrollTop=d.y});
c.play()}else g.Pu(a.T,!0),a.B.scrollTop=b.Mo.offsetTop,g.Pu(a.T,!1)},m2=function(a){return a.u&&a.u.card?a.u.card:a.A[0]&&a.A[0].card?a.A[0].card:null},gpa=function(a,b){return g.Ua(a.A,function(c){return c.card.id==b})},n2=function(a,b,c){b2.call(this,a,b);
this.annotation=c;this.isActive=!1},lpa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},o2=function(a,b,c){n2.call(this,a,b,c);
this.w=null;this.G=!1;this.A=null;this.B=!1;this.u=this.D=this.C=null},p2=function(a,b,c){n2.call(this,a,b,c);
this.J=this.C=this.K=!1;this.G=5E3;this.B=null;this.H=g.Md("DIV","iv-promo-contents");this.w=this.A=this.u=null;this.D=new g.J(function(){this.u.setAttribute("aria-hidden",!0);g.ug(this.A,!1);g.ug(this.w,!0)},700,this);
g.H(this,this.D)},mpa=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.G=b.collapse_delay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.o.setAttribute("aria-hidden",!0);a.o.setAttribute("aria-label","Promotion");a.o.tabIndex=0;var e=P1(a.annotation),f=b.image_url;if(f){var k=g.Md("DIV",["iv-promo-img","iv-click-target"]);f=g.Md("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.Md("SPAN","iv-promo-video-duration",b.video_duration),
k.appendChild(f)):b.playlist_length&&(f=g.Md("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.Li(k,e,a.annotation.id,b.session_data,void 0,c)}e?(f=g.Md("A","iv-promo-txt"),g.Sc(f,M1(e)),a.u=f):a.u=g.Md("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.Md("P",null,g.Md("STRONG",null,b.text_line_1));var m=g.Md("P",null,g.Md("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");g.R(a.context.Xa.experiments,
"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.Md("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.Md("BUTTON",["iv-button","iv-promo-button"],g.Md("SPAN","iv-button-content",f));var q=g.Md("DIV","iv-promo-button-container");q.appendChild(f);e&&a.Li(a.o,e,a.annotation.id,b.session_data,void 0,c)}g.K(a.u,"iv-click-target");e&&a.Li(a.u,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=g.Md("P",null,g.Md("SPAN",null,b.text_line_1)),
m=g.Md("P",null,g.Md("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.Md("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.K(a.u,"iv-click-target"),e&&a.Li(a.u,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.u.appendChild(l);m&&a.u.appendChild(m);a.H.appendChild(a.u);q&&a.H.appendChild(q);c=g.Md("DIV","iv-promo-actions");a.w=g.Md("BUTTON",["iv-promo-expand","ytp-button"]);a.w.title="Expand";a.context.o.ga(a.w,"click",g.Na(a.Bp,5E3),a);c.appendChild(a.w);g.ug(a.w,!1);
a.context.o.ga(a.o,"mouseover",a.PC,a);a.context.o.ga(a.o,"mouseout",a.OC,a);a.context.o.ga(a.o,"touchend",g.Na(a.Bp,5E3),a);a.A=g.Md("BUTTON",["iv-promo-close","ytp-button"]);a.A.title="Close";a.context.o.ga(a.A,"click","cta"==a.annotation.style&&b.text_line_3?a.IC:a.HC,a);c.appendChild(a.A);g.jn(a.o,d);k&&(a.o.appendChild(k),n&&k.appendChild(n));a.o.appendChild(a.H);a.o.appendChild(c)},q2=function(a){a.C||a.J||a.B||(g.K(a.o,"iv-promo-collapsed"),a.C=!0,a.D.start())},r2=function(a){a.D.stop();
a.C&&(g.ln(a.o,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.C=!1,a.u&&a.u.removeAttribute("aria-hidden"),g.ug(a.w,!1),g.ug(a.A,!0))},t2=function(a,b){a.B||(a.B=g.dl(function(){s2(this);
q2(this)},b,a))},s2=function(a){a.B&&(g.u.clearTimeout(a.B),a.B=null)},u2=function(a){g.AP.call(this,a);
this.J=!1;this.H=0;this.D={};this.T=new Yoa(a);this.B=new g.Q(this);g.H(this,this.B);this.C=this.w=null;this.B.M(this.player,"onVideoAreaChange",(0,g.x)(this.R,this,"onVideoAreaChange"));this.B.M(this.player,"onHideControls",(0,g.x)(this.R,this,"onHideControls"));this.B.M(this.player,"onShowControls",(0,g.x)(this.R,this,"onShowControls"));this.B.M(this.player,"resize",(0,g.x)(this.R,this,"resize"));this.B.M(this.player,"presentingplayerstatechange",(0,g.x)(this.R,this,"presentingplayerstatechange"));
this.subscribe("presentingplayerstatechange",this.FJ,this);this.subscribe("resize",this.qn,this);this.player.O().G.subscribe("vast_info_card_add",this.ty,this);this.P=new g.Q(this);g.H(this,this.P);this.U=g.Md("DIV","video-custom-annotations");this.u=new g.W({F:"div",X:["ytp-player-content","ytp-iv-player-content"]});g.H(this,this.u);g.WK(this.player,this.u.element,4);this.u.hide();this.A=new g.W({F:"div",X:["ytp-iv-video-content"]});g.H(this,this.A);g.Pd(this.A.element,g.Md("DIV","video-annotations",
this.U));this.G=this.o=null;this.K=[];npa(this)&&this.load();var b=g.Nd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.xi(this,function(){g.Sd(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},v2=function(){var a=g.Md("DIV",["annotation",
"annotation-type-custom"]);g.ug(a,!1);return a},w2=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},npa=function(a){var b=a.player.O();
a=a.player.getVideoData();return 1==(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.hA||null!==b.G.get(a.videoId)},x2=function(a,b,c){a.J=!0;
a.C=g.zp(b,c)},y2=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ka(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(y2(a,e))}return c},z2=function(a,b,c){return!(a.loaded&&a.H==b&&a.player.getVideoData().videoId==
c)},opa=function(a){var b=a.player.getVideoData();
if(b.Bd){var c=a.player.O().G.get(b.videoId);if(c){var d={format:"XML",od:{},method:"POST",withCredentials:!0};d.Wc=(0,g.x)(function(e,f,k){z2(this,e,f)||(e=g.tp(k)&&k.responseXML?k.responseXML:null)&&A2(this,e)},a,a.H,b.videoId);
g.Wo()&&(d.Wc=B2(a,d.Wc));d.sb={ic_only:"1"};C2(d,c);a.J=!0;g.zp(b.Bd,d)}}},C2=function(a,b){a.method="POST";
a.sb=a.sb||{};b.Dl&&(a.sb.ic_coll=b.Dl);b.El&&(a.sb.ic_xml=b.El);b.ds&&(a.sb.ic_track=b.ds)},E2=function(a){var b=new g.W({F:"div"});
g.ug(b.element,!1);var c=new g2(a.player,b.element,D2(a));g.H(c,b);b.o(a.u.element);c.Ck();return c},D2=function(a){if(!a.G){var b=new u1(a);
g.H(a,b);var c=new g.d_(a);g.H(a,c);a.G=new $oa(b,c,a.player.O(),a.player.getVideoData(),a.T,a.player,a.Sb)}return a.G},A2=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.fB();if(e){var f=g.eB();f&&g.XA(e,f,[g.KA(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var k=y2(a,d[e]);f=null;try{if(k){var l=k.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var q=J1(k.type,ppa),t=J1(k.style,qpa),v=I1(k.data),y=0!=v.length?JSON.parse(v):{},C=Roa(k.action);f=n&&q?new O1(n,q,t,C,y):null}else f=null}catch(M){}if(f){a:{switch(f.type){case "branding":case "promotion":k=!0;break a}k=
!1}if(k){k=a;m=f;var B=v2(),G=null;switch(m.type){case "branding":if(k.player.O().fc)break;k.u.element.appendChild(B);G=new o2(B,D2(k),m);break;case "promotion":g.WK(k.player,B,4),G=new p2(B,D2(k),m)}G&&G.Ck();if(k=G)g.H(a,k),a.D[f.id]=k}else if("card"==f.type||"drawer"==f.type){a.o||(a.o=E2(a),g.H(a,a.o));if("card"==f.type){if(c=a.o,G=f&&f.data&&f.data.card_type)switch(k=f.data.tracking||{},k={Dv:k.impression,click:k.click,close:k.close,Ez:k.teaser_impression,Qn:k.teaser_click},m=f.data.tracking_params||
{},B=null,G){case "collaborator":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Fb:f.data.session_data||{},sponsored:f.data.sponsored||!1,tc:k,Cd:m.card?g.KA(m.card):null,zd:m.teaser?g.KA(m.teaser):null,Qc:m.icon?g.KA(m.icon):null,channelId:f.data.channel_id,customMessage:f.data.custom_message?f.data.custom_message:null,Hy:f.data.image_url,title:f.data.title,
metaInfo:f.data.meta_info,url:L1({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};i2(c,f);break;case "episode":case "movie":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Fb:f.data.session_data||{},sponsored:f.data.sponsored||!1,tc:k,Cd:m.card?g.KA(m.card):null,zd:m.teaser?g.KA(m.teaser):null,Qc:m.icon?g.KA(m.icon):
null,Dh:f.data.image_url,Mt:f.data.badge_symbol||"",priceText:f.data.price_text||"",title:f.data.title,metaInfo:f.data.meta_info,xD:!!f.data.is_paygated,CM:!!f.data.user_has_entitlement,url:L1({target:f.data.target||"new",value:f.data.url})};i2(c,f);break;case "playlist":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Fb:f.data.session_data||{},sponsored:f.data.sponsored||
!1,tc:k,Cd:m.card?g.KA(m.card):null,zd:m.teaser?g.KA(m.teaser):null,Qc:m.icon?g.KA(m.icon):null,Dh:f.data.image_url,playlistVideoCount:f.data.playlist_video_count,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,url:L1({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};i2(c,f);break;case "poll":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,
startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Fb:f.data.session_data||{},sponsored:f.data.sponsored||!1,tc:k,Cd:m.card?g.KA(m.card):null,zd:m.teaser?g.KA(m.teaser):null,Qc:m.icon?g.KA(m.icon):null,title:f.data.title,choices:f.data.choices,ee:f.data.hasOwnProperty("old_vote")?f.data.old_vote:null,Ah:f.data.signin_url?L1({target:"current",value:f.data.signin_url}):null,OM:f.data.hasOwnProperty("xsrf_token")?f.data.xsrf_token:null};i2(c,f);break;case "productListing":f.data.signin_url&&(B=L1({target:"current",
value:f.data.signin_url}));G=[];for(var I=f.data.offers||[],F=0;F<I.length;F++)G.push(new Xoa(g.Zc(I[F].merchant),g.Zc(I[F].price)));f={KQ:!1,id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Fb:f.data.session_data||{},sponsored:f.data.sponsored||!1,tc:k,Cd:m.card?g.KA(m.card):null,zd:m.teaser?g.KA(m.teaser):null,Qc:m.icon?g.KA(m.icon):null,imageUrl:f.data.image_url,
displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,xl:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:L1({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url}),Ah:B,VQ:f.data.signin_title?f.data.signin_title:null,UQ:f.data.signin_message?f.data.signin_message:null,offers:G};i2(c,f);break;case "simple":f={id:f.id,timestamp:f.data.timestamp||
0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Fb:f.data.session_data||{},sponsored:f.data.sponsored||!1,tc:k,Cd:m.card?g.KA(m.card):null,zd:m.teaser?g.KA(m.teaser):null,Qc:m.icon?g.KA(m.icon):null,imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,xl:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,
customMessage:f.data.custom_message?f.data.custom_message:null,url:L1({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};i2(c,f);break;case "video":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Fb:f.data.session_data||{},sponsored:f.data.sponsored||!1,tc:k,Cd:m.card?g.KA(m.card):null,zd:m.teaser?g.KA(m.teaser):
null,Qc:m.icon?g.KA(m.icon):null,Dh:f.data.image_url,videoDuration:f.data.video_duration||null,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,isLiveNow:!!f.data.is_live_now,url:L1({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})},i2(c,f)}}else epa(a.o,f);c=!0}}}c&&(h1(a.player),a.qn())},rpa=function(a,b){var c=!1;
a.o||(a.o=E2(a),g.H(a,a.o));for(var d=g.p(b.cards||[]),e=d.next();!e.done;e=d.next())fpa(a.o,e.value.cardRenderer),c=!0;c&&(c=a.o,d=b.headerText?g.WB(b.headerText):"",g.Xd(c.wa,d),c.P&&c.P.setAttribute("title",d),c.ba=b.trackingParams?g.KA(b.trackingParams):null,c.U=b.closeButton.infoCardIconRenderer.trackingParams?g.KA(b.closeButton.infoCardIconRenderer.trackingParams):null,c.J=b.icon.infoCardIconRenderer.trackingParams?g.KA(b.icon.infoCardIconRenderer.trackingParams):null,h1(a.player),a.qn())},
spa=function(a,b,c,d,e){if(!a.player.O().fc){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new N1("openUrl","click",new K1("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var k=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:k.height,image_type:1,image_url:k.url,image_width:k.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;b=b.subscribeButton.subscribeButtonRenderer;b.subscribed?(e=g.WB(b.subscriberCountWithUnsubscribeText),k=g.WB(b.subscriberCountText)):(e=g.WB(b.subscriberCountText),k=g.WB(b.subscriberCountWithSubscribeText));var l="";b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&b.signInEndpoint.webNavigationEndpointData.url&&(l=b.signInEndpoint.webNavigationEndpointData.url);b={subscribeText:g.WB(b.unsubscribedButtonText),
subscribeCount:e,unsubscribeText:g.WB(b.subscribedButtonText),unsubscribeCount:k,enabled:b.enabled,classic:!1,subscribed:b.subscribed,feature:"iv",signInUrl:l};d.standalone_subscribe_button_data=b}f=new O1(c,"branding","branding",f,d);d=v2();a.u.element.appendChild(d);f=new o2(d,D2(a),f);f.Ck();g.H(f,f);a.D[c]=f}},B2=function(a,b){return(0,g.x)(function(){if(!this.ha()){var c=Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Na.apply(window,c);this.K.push(g.Uo(b))}},a)},k1={},l1=null;g.Pa(p1,g.mn);g.h=p1.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.w;else if(1==this.o)return!1;m1(this);this.startTime=a=(0,g.A)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.B();this.Ud("play");-1==this.o&&this.Ud("resume");this.o=1;var b=g.Ma(this);b in k1||(k1[b]=this);n1();o1(this,a);return!0};
g.h.stop=function(a){m1(this);this.o=0;a&&(this.progress=1);q1(this,this.progress);this.Ud("stop");this.A()};
g.h.pause=function(){1==this.o&&(m1(this),this.o=-1,this.Ud("pause"))};
g.h.Y=function(){0==this.o||this.stop(!1);this.Ud("destroy");p1.wb.Y.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.er=function(){this.Ud("animate")};
g.h.Ud=function(a){this.dispatchEvent(new r1(a,this))};
g.Pa(r1,g.Uj);g.Pa(s1,p1);s1.prototype.C=g.Ea;s1.prototype.er=function(){this.C();s1.wb.er.call(this)};
s1.prototype.A=function(){this.C();s1.wb.A.call(this)};
s1.prototype.B=function(){this.C();s1.wb.B.call(this)};
g.Pa(t1,s1);t1.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.r(u1,g.E);u1.prototype.ga=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.Yq(a,b,c);this.o.push(a);return a};
u1.prototype.Zp=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.hr(a,b,c);this.o.push(a);return a};
u1.prototype.Ta=function(a){g.Zq(a);g.ab(this.o,a)};
u1.prototype.Y=function(){g.Zq(this.o);this.o.length=0;g.E.prototype.Y.call(this)};g.r(x1,g.AP);g.h=x1.prototype;g.h.load=function(){g.AP.prototype.load.call(this);if(!z1(this)){var a=g.MC(this.player.getVideoData());if(a)a=w1(a,y1(this)),A1(this,a);else{var b=this.player.getVideoData();a=b.videoId;this.A&&this.A.abort();a={method:"POST",Wc:(0,g.x)(this.qI,this,a),od:{v:a},withCredentials:!0};this.J&&(a.od.ptype="embedded");var c=this.player.getVideoData().tu;c&&(a.sb={ad_tracking:c});if(b=g.LC(b))if(b=g.Bc(b),b=g.zc(b))this.A=g.zp(b,a)}}};
g.h.unload=function(){A1(this,null);this.A&&(this.A.abort(),this.A=null);g.AP.prototype.unload.call(this)};
g.h.wc=function(a,b){if(!z1(this))return null;if("loadCustomEndscreenRenderer"==a){var c=w1(b,"new");A1(this,c);return!0}return null};
g.h.getOptions=function(){return z1(this)?["loadCustomEndscreenRenderer"]:[]};
g.h.qI=function(a,b){var c=this.A=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=w1(c,y1(this)))}A1(this,c)};
g.h.uw=function(){if(this.u&&this.u.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<F2.length;f++){var k=Math.abs(b.width-F2[f]);if(-1==e||d>=k)e=f,d=k}d=G2[e];this.w&&g.ag(this.w.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.u.elements.length;++b)if(f=this.u.elements[b].id,e=this.o[f],k=this.D[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.sg(e.element,Math.round(k.width*a.width),f);g.ig(e.element,m,n);g.ln(e.element,tpa);m=k.left+k.width/2;k=k.top+l/2;g.K(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.ln(e.element,G2);g.K(e.element,d);(e=g.yd(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.ag(e,"height",f+"px")}}}}};
g.h.hE=function(a){if(this.u)if("ytp-ce-in-endscreen"==a.getId())F1(this,this.u.impressionUrls),(a=g.fB())&&this.u.visualElement&&g.YA(a,this.u.visualElement);else{a=a.getId().substring(15);var b=this.o[a],c=this.D[a];g.K(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.K(b,"ytp-ce-shown");F1(this,c.impressionUrls);(b=g.fB())&&g.YA(b,c.visualElement);this.player.O().vb&&this.player.ka("endscreenelementshown",a)}};
g.h.iE=function(a){if("ytp-ce-in-endscreen"!=a.getId()){a=a.getId().substring(15);var b=this.o[a];g.kn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.kn(b,"ytp-ce-shown");this.player.O().vb&&this.player.ka("endscreenelementhidden",a)}};
g.h.hL=function(a){var b=this;a.target===window&&(new g.J(function(){for(var c in b.o)g.ln(b.o[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.Sx=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.hn(c,"ytp-ce-element");){g.hn(c,"subscribe-label")&&G1(this,a);if(g.hn(c,"ytp-ce-channel-subscribe"))return;c=g.Vd(c)}if(!c||g.hn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.kr(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.lM?(G1(this,a),this.lz(),this.player.pauseVideo(),c=g.Bc(C1(this,a.targetUrl)),c=g.zc(c),g.BM(c,void 0,a.Fb)):(c=this.player.getVideoData().ac,
c=(0,g.x)(this.cM,this,c,C1(this,a.targetUrl),a.Fb),c=(0,g.x)(this.lz,this,c),G1(this,a,c))}}};
g.h.cM=function(a,b,c){var d=g.fp(b);a&&d&&(d.v||d.list)?g.kT(this.player.app,d.v,c,d.list,!1,void 0):g.AM(b,c)};
g.h.nq=function(a,b){g.hn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.K(a.element,"ytp-ce-element-hover"):this.player.O().o?(new g.J(function(){g.K(a.element,"ytp-ce-element-hover")},200)).start():g.K(a.element,"ytp-ce-element-hover"),F1(this,b.lD),E1(this,b.id,!0))};
g.h.kr=function(a,b){g.kn(a.element,"ytp-ce-element-hover");g.kn(a.element,"ytp-ce-force-expand");E1(this,b.id,!1)};
g.h.lz=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var F2=[346,426,470,506,570,640,853,1280,1920],G2="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),tpa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var Toa={UN:"current",nP:"new"};var Uoa={CLOSE:"close",qP:"openUrl",bB:"subscribe"},Voa={NN:"click",CLOSE:"close",FO:"hidden",NP:"rollOut",OP:"rollOver",RP:"shown"};var qpa={qN:"anchored",xA:"branding",CHANNEL:"channel",TN:"cta",HO:"highlightText",WO:"label",PLAYLIST:"playlist",AP:"popup",VP:"speech",bB:"subscribe",fQ:"title",VIDEO:"video",tQ:"website"},ppa={xA:"branding",EN:"card",aO:"drawer",GO:"highlight",dP:"marker",FP:"promotion",TEXT:"text",vQ:"widget"};S1.prototype.u=function(a,b){var c=g.de(b.target,"label");c&&g.L(c,"iv-card-poll-choice-focused",a)};
S1.prototype.A=function(a,b){var c=g.de(b.target,null,"iv-card-poll",void 0);if(c)if(a.Ah)g.Bd("iv-card-sign-in-button",c).click();else{var d=parseInt(Foa(b.target),10);if(null==a.ee)a.choices[d].count++,a.ee=d;else if(a.ee!=d){var e=a.choices[a.ee];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.ee=d}else e=a.choices[a.ee],e.count=Math.max(e.count-1,0),a.ee=null;U1(a,c);g.Dp(this.o.videoData.Bd,{od:{action_poll_vote:1},sb:{poll_id:a.id,index:d,session_token:a.OM}});R1(this.o.logger,a.tc.click,
void 0,5);(c=g.fB())&&a.Cd&&g.ZA(c,a.Cd)}};g.r(b2,g.E);g.h=b2.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.LD(a,b,{id:c});g.H(this,a);a.namespace="annotations_module";d&&g1(a).subscribe("onEnter",d,this);e&&g1(a).subscribe("onExit",e,this);g.SK(this.context.ca,[a])};
g.h.Ck=function(){this.context.u.subscribe("resize",this.zl,this)};
g.h.Li=function(a,b,c,d,e,f){this.context.o.ga(a,"click",g.Na(this.Cm,b,c,d,e||[],f||0),this);this.context.o.ga(a,"touchstart",g.Na(function(){this.xs=!1}),this);
this.context.o.ga(a,"touchmove",g.Na(function(){this.xs=!0}),this)};
g.h.Cm=function(a,b,c,d,e,f){if(this.xs)return!1;f&&(f.stopPropagation(),f.preventDefault());dpa(this,a,c,d,e);return!1};
g.h.show=function(){};
g.h.hide=function(){};
g.h.destroy=function(){g.Sd(this.o)};
g.h.zl=function(){};g.r(g2,b2);g.h=g2.prototype;g.h.isAvailable=function(){var a;if(a=!!this.A.length)(a=this.w.getRootNode())?(a=g.tg(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.zl=function(){var a=this.isAvailable();g.ug(this.o,a);g.L(this.context.ca.getRootNode(),"ytp-iv-drawer-enabled",a);h1(this.w)};
g.h.destroy=function(){var a=g.KK(g.yK(this.w));a&&a.mq(!1,void 0);this.w.getRootNode().removeChild(this.D);g.Jo(this.V);g.Zq(this.aa);this.fa&&this.fa.dispose();this.G&&this.G.dispose();b2.prototype.destroy.call(this)};
g.h.EE=function(a){this.da.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.B.scrollTop+=a};
g.h.mz=function(a){if(!g.hn(this.w.getRootNode(),"ytp-cards-teaser-shown")){if(this.u!=a){var b=g.fB(),c=this.u?this.u.card.Qc:this.J;b&&c&&j1(b,[c]);this.u=a;j2(this)}"none"!=this.o.style.display&&(2==this.context.ca.getPresentingPlayerType()?b=1==(isNaN(void 0)?this.context.ca.getAdState():void 0):(b=isNaN(void 0)?this.context.ca.getPlayerState():void 0,b=1==b||0==b&&0===this.context.ca.getCurrentTime()),b&&a.card.teaserDurationMs&&(b={teaserText:a.card.teaserText,durationMs:a.card.teaserDurationMs},
(c=g.KK(g.yK(this.w)))&&c.mq(!0,b)));this.la.isActive()||((!this.C||!this.da.isActive()&&this.Z)&&l2(this,a),this.la.start(910+a.card.teaserDurationMs))}};
g.h.UL=function(a){this.C||(this.u=a,j2(this),l2(this,a),e2(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1))};
g.h.EB=function(){if(this.C){R1(this.context.logger,m2(this).tc.close);var a=g.fB();a&&this.U&&g.ZA(a,this.U);f2(this)}};
g.h.SB=function(){g.L(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.h.JD=function(){var a=g.fB(),b=m2(this);b=b?b.Qc:this.J;a&&b&&i1(a,[b])};
g.h.ID=function(){var a=g.fB(),b=m2(this);b=b?b.Qc:this.J;a&&b&&j1(a,[b])};
g.h.MD=function(){var a=m2(this);R1(this.context.logger,a.tc.Ez);var b=g.fB();b&&a&&i1(b,[a.zd,a.Qc])};
g.h.LD=function(){var a=g.fB(),b=m2(this);a&&b&&j1(a,[b.zd])};
g.h.KD=function(a){var b=m2(this),c=g.fB();this.u?a?(a=this.context.logger,R1(a,b.tc.Qn),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.zd&&g.ZA(c,b.zd)):(a=this.context.logger,R1(a,b.tc.Qn),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.Qc&&g.ZA(c,b.Qc)):(a=this.context.logger,R1(a,b.tc.Qn),a.o.sendVideoStatsEngageEvent(4,void 0),c&&this.J&&g.ZA(c,this.J))};g.r(n2,b2);n2.prototype.Ck=function(){b2.prototype.Ck.call(this);lpa(this)};
n2.prototype.show=function(){b2.prototype.show.call(this);var a=g.fB(),b=this.annotation.data;a&&b&&(b=b.session_data)&&i1(a,[g.KA(b.itct)])};
n2.prototype.hide=function(){b2.prototype.hide.call(this);var a=g.fB(),b=this.annotation.data;a&&b&&(b=b.session_data)&&j1(a,[g.KA(b.itct)])};g.r(o2,n2);g.h=o2.prototype;g.h.dM=function(a,b,c,d){this.A.stop();if(!this.B){var e=g.tg(a);this.u||(g.rg(a,e.width),g.rg(b,e.width));g.ag(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.ag(c,"right","1px");this.B=!0;g.ug(a,!0);this.C=new g.J(function(){g.K(this.o,"iv-branding-active")},0,this);
this.C.start()}};
g.h.jD=function(a,b){g.kn(this.o,"iv-branding-active");this.D=new g.J((0,g.x)(function(){g.ug(a,!1);this.u||g.rg(b,0)},this),250);
this.D.start();this.B=!1};
g.h.show=function(){if(!this.isActive){n2.prototype.show.call(this);if(!this.G){g.K(this.o,"iv-branding");var a=this.annotation.data;this.w=g.Md("IMG",{"aria-label":"Channel watermark",src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.ug(this.w,!1);var b=g.Md("DIV","branding-img-container",this.w);this.o.appendChild(b);(b=P1(this.annotation))&&this.Li(this.w,b,this.annotation.id,a.session_data);if(a.channel_name){var c=g.Md("DIV","iv-branding-context-name");
g.Xd(c,a.channel_name);var d=g.Md("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.u=new g.MQ(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.ca),this.u.o(d);b=g.Md("DIV","iv-branding-context-subscribe-caret");c=g.Md("DIV","branding-context-container-inner",b,c,d);g.ug(c,!1);d=g.Md("DIV","branding-context-container-outer",c);g.ag(d,"right",
a.image_width+"px");this.o.appendChild(d);this.A=new g.J(g.Na(this.jD,c,d),500,this);g.H(this,this.A);this.context.o.ga(this.o,"mouseover",(0,g.x)(this.dM,this,c,d,b,a.image_height));this.context.o.ga(this.o,"mouseout",(0,g.x)(this.A.start,this.A,void 0))}this.G=!0}g.ug(this.o,!0);this.isActive=!0;if(this.w){a=this.w;var e=void 0===e?0:e;b=g.mg(a);c=g.tg(a);b=(new g.Yf(b.x,b.y,c.width,c.height)).width;g.ig(a,b);e=new t1(a,[b,a.offsetTop],[b-b-e,a.offsetTop],200,Goa);g.H(this,e);this.context.w.ga(e,
"begin",g.Na(g.ug,a,!0));e.play()}}};
g.h.hide=function(){this.isActive&&(n2.prototype.hide.call(this),g.ug(this.o,!1),this.isActive=!1)};
g.h.destroy=function(){this.u&&(this.u.dispose(),this.u=null);n2.prototype.destroy.call(this)};g.r(p2,n2);g.h=p2.prototype;g.h.show=function(){this.isActive||(n2.prototype.show.call(this),this.K||(mpa(this),this.K=!0),g.ug(this.o,!0),g.dl(function(){g.kn(this.o,"iv-promo-inactive")},100,this),this.o.removeAttribute("aria-hidden"),this.isActive=!0,s2(this),r2(this),t2(this,this.G))};
g.h.hide=function(){this.isActive&&(g.K(this.o,"iv-promo-inactive"),this.isActive=!1,this.o.setAttribute("aria-hidden",!0))};
g.h.Cm=function(a,b,c,d,e,f){return this.C?!1:n2.prototype.Cm.call(this,a,b,c,d,e,f)};
g.h.Bp=function(a,b){b.stopPropagation();r2(this);t2(this,a);this.u.focus()};
g.h.PC=function(a){this.J=!0;this.Bp(500,a)};
g.h.OC=function(){this.J=!1;q2(this)};
g.h.HC=function(a){a.stopPropagation();this.hide()};
g.h.IC=function(a){a.stopPropagation();s2(this);this.C=!0;g.K(this.o,"iv-promo-collapsed-no-delay");this.D.start()};
g.h.destroy=function(){this.D.dispose();n2.prototype.destroy.call(this)};g.r(u2,g.AP);g.h=u2.prototype;g.h.wc=function(a,b){if(!w2(this.player.O().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.c_(b);c&&A2(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(k2(this.o,b),h1(this.player)),!0}return null};
g.h.getOptions=function(){return w2(this.player.O().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.qn=function(){if(this.A){var a=g.EK(this.player).getVideoContentRect(!0);g.sg(this.A.element,a.width,a.height);g.ig(this.A.element,a.left,a.top)}if(this.o){var b=g.NK(this.player);a=this.o;b=b.width;g.L(a.D,"iv-drawer-small",426>=b);g.L(a.D,"iv-drawer-big",1280<=b)}};
g.h.FJ=function(a){this.dc(a.state);g.U(a.state,2)&&(this.Vj()&&this.rw()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.mq(!1))};
g.h.load=function(){g.AP.prototype.load.call(this);this.dc(g.DK(this.player));this.H++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.x)(this.sI,this,b,this.H),d=(0,g.x)(function(){this.C=null},this);
g.Wo()&&(c=B2(this,c));c={format:"XML",Wc:c,onError:d,od:{}};a.isPharma&&(c.od.pharma="1");c.method="POST";c.withCredentials=!0;(b=this.player.O().G.get(b))&&C2(c,b);b=b&&(b.El||b.Dl);if(!a.sl||b)a.Bd?x2(this,a.Bd,c):(this.w=(0,g.x)(this.fE,this,c),this.player.addEventListener("videodatachange",this.w));g.WK(this.player,this.A.element,4);this.qn();(b=a.Ja&&a.Ja.cards&&a.Ja.cards.cardCollectionRenderer||null)&&rpa(this,b);(b=Eoa(a))&&b.featuredChannel&&spa(this,b.featuredChannel,b.annotationId||"branding",
a.videoId||null,a.eventId||null)};
g.h.dc=function(a){a=!a.isCued()&&!g.U(a,1024);g.Pu(this.u,a);g.Pu(this.A,a)};
g.h.fE=function(a){var b=this.player.getVideoData();b.Bd&&(this.w&&(this.player.removeEventListener("videodatachange",this.w),this.w=null),x2(this,b.Bd,a))};
g.h.unload=function(){g.GQ(this.player.app,"annotations_module",void 0);g.Ib(this.D,function(a){a.destroy()});
this.G=null;this.o&&(this.o.destroy(),this.o=null,h1(this.player));this.J=!1;this.C&&(this.C.abort(),this.C=null);this.D={};this.u.hide();g.AP.prototype.unload.call(this);g.Ou(this.A);this.w&&(this.player.removeEventListener("videodatachange",this.w),this.w=null)};
g.h.sI=function(a,b,c){this.C=null;!z2(this,b,a)&&(a=g.tp(c)&&c.responseXML?c.responseXML:null)&&(A2(this,a),g.K(this.player.getRootNode(),"iv-module-loaded"))};
g.h.ty=function(a){a==this.player.getVideoData().videoId&&(this.loaded?opa(this):this.load())};
g.h.Vj=function(){return!!this.o&&this.o.isAvailable()};
g.h.rw=function(){this.Vj();return!!this.o&&this.o.C};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Vj();this.o&&(a?c?e2(this.o,c,b):e2(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):f2(this.o))};
g.h.mq=function(a,b){this.player.R(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.Y=function(){this.player.O().G.unsubscribe("vast_info_card_add",this.ty,this);g.kn(this.player.getRootNode(),"ytp-iv-drawer-open");for(var a=this.K,b=0,c=a.length;b<c;b++)g.Xo(a[b]);this.K.length=0;g.AP.prototype.Y.call(this)};g.PP.annotations_module=u2;g.PP.creatorendscreen=x1;})(_yt_player);
